# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or create alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create[{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.createname: 'Emanuel', city: cities.first)


# Breeds:
# Source http://www.justdogbreeds.com/dog-breeds.html

Breed.create(breed: "Affenpinscher")
Breed.create(breed: "Afghan ")
Breed.create(breed: "Airedale Terrier")
Breed.create(breed: "Akita")
Breed.create(breed: "Alaskan Malamute")
Breed.create(breed: "Standard American Eskimo Dog")
Breed.create(breed: "Miniature American Eskimo Dog")
Breed.create(breed: "Toy American Eskimo Dog")
Breed.create(breed: "American Foxhound")
Breed.create(breed: "American Staffordshire Terrier")
Breed.create(breed: "American Water Spaniel")
Breed.create(breed: "Anatolian Shepherd Dog")
Breed.create(breed: "Australian Cattle Dog")
Breed.create(breed: "Australian Shepherd")
Breed.create(breed: "Australian Terrier")
Breed.create(breed: "Basenji")
Breed.create(breed: "Basset ")
Breed.create(breed: "Beagle")
Breed.create(breed: "Bearded Collie")
Breed.create(breed: "Beauceron")
Breed.create(breed: "Bedlington Terrier")
Breed.create(breed: "Belgian Malinois")
Breed.create(breed: "Belgian Sheepdog")
Breed.create(breed: "Belgian Tervuren")
Breed.create(breed: "Bernese Mountain Dog")
Breed.create(breed: "Bichon ")
Breed.create(breed: "Black and Tan Coonhound")
Breed.create(breed: "Black Russian Terrier")
Breed.create(breed: "Bloodhound")
Breed.create(breed: "Border Collie")
Breed.create(breed: "Border Terrier")
Breed.create(breed: "Borzoi")
Breed.create(breed: "Boston Terrier")
Breed.create(breed: "Bouvier des Flandres")
Breed.create(breed: "Boxer")
Breed.create(breed: "Briard")
Breed.create(breed: "Brittany")
Breed.create(breed: "Brussels Griffon")
Breed.create(breed: "Bulldog")
Breed.create(breed: "Bullmastiff")
Breed.create(breed: "Bull ")
Breed.create(breed: "Cairn ")
Breed.create(breed: "Canaan ")
Breed.create(breed: "Cardigan Welsh Corgi")
Breed.create(breed: "Cavalier King Charles Spaniel")
Breed.create(breed: "Chesapeake Bay Retriever")
Breed.create(breed: "Chihuahua")
Breed.create(breed: "Chinese Crested")
Breed.create(breed: "Chinese Shar-Pei")
Breed.create(breed: "Chow Chow")
Breed.create(breed: "Clumber Spaniel")
Breed.create(breed: "Cocker Spaniel")
Breed.create(breed: "Collie")
Breed.create(breed: "Curly-Coated Retriever")
Breed.create(breed: "Dachshund")
Breed.create(breed: "Dalmatian")
Breed.create(breed: "Dandie Dinmont Terrier")
Breed.create(breed: "Doberman Pinscher")
Breed.create(breed: "Dogue de Bordeaux")
Breed.create(breed: "English Cocker Spaniel")
Breed.create(breed: "English Foxhound")
Breed.create(breed: "English Setter")
Breed.create(breed: "English Springer Spaniel")
Breed.create(breed: "English Toy Spaniel")
Breed.create(breed: "Field ")
Breed.create(breed: "Finnish Spitz")
Breed.create(breed: "Flat-Coated Retriever")
Breed.create(breed: "French Bulldog")
Breed.create(breed: "German Pinscher")
Breed.create(breed: "German Shepherd Dog")
Breed.create(breed: "German Shorthaired Pointer")
Breed.create(breed: "German Wirehaired Pointer")
Breed.create(breed: "Giant Schnauzer")
Breed.create(breed: "Glen of Imaal Terrier")
Breed.create(breed: "Golden Retriever")
Breed.create(breed: "Gordon Setter")
Breed.create(breed: "Great ")
Breed.create(breed: "Greater Swiss Mountain Dog")
Breed.create(breed: "Great Pyrenees")
Breed.create(breed: "Greyhound")
Breed.create(breed: "Harrier")
Breed.create(breed: "Havanese")
Breed.create(breed: "Ibizan ")
Breed.create(breed: "Irish ")
Breed.create(breed: "Irish Water Spaniel")
Breed.create(breed: "Irish Wolfhound")
Breed.create(breed: "Italian Greyhound")
Breed.create(breed: "Jack Russell Terrier")
Breed.create(breed: "Japanese Chin")
Breed.create(breed: "Keeshond")
Breed.create(breed: "Kerry Blue Terrier")
Breed.create(breed: "Komondor")
Breed.create(breed: "Kuvasz")
Breed.create(breed: "Labrador Retriever")
Breed.create(breed: "Lakeland Terrier")
Breed.create(breed: "Lhasa ")
Breed.create(breed: "Lowchen")
Breed.create(breed: "Maltese")
Breed.create(breed: "Standard Manchester Terrier")
Breed.create(breed: "Mastiff")
Breed.create(breed: "Miniature Bull Terrier")
Breed.create(breed: "Miniature Pinscher")
Breed.create(breed: "Miniature Poodle")
Breed.create(breed: "Miniature Schnauzer")
Breed.create(breed: "Neapolitan Mastiff")
Breed.create(breed: "Newfoundland")
Breed.create(breed: "Norfolk Terrier")
Breed.create(breed: "Norwegian Elkhound")
Breed.create(breed: "Norwich Terrier")
Breed.create(breed: "Nova Scotia Duck Tolling Retriever")
Breed.create(breed: "Old English Sheepdog")
Breed.create(breed: "Otterhound")
Breed.create(breed: "Papillon")
Breed.create(breed: "Parson Russell Terrier")
Breed.create(breed: "Pekingese")
Breed.create(breed: "Pembroke Welsh Corgi")
Breed.create(breed: "Petit Basset Griffon Vendeen")
Breed.create(breed: "Pharaoh Hound")
Breed.create(breed: "Plott")
Breed.create(breed: "Pointer")
Breed.create(breed: "Polish Lowland Sheepdog")
Breed.create(breed: "Pomeranian")
Breed.create(breed: "Portuguese Water Dog")
Breed.create(breed: "Pug")
Breed.create(breed: "Puli")
Breed.create(breed: "Rhodesian Ridgeback")
Breed.create(breed: "Rottweiler")
Breed.create(breed: "Saint ")
Breed.create(breed: "Saluki")
Breed.create(breed: "Samoyed")
Breed.create(breed: "Schipperke")
Breed.create(breed: "Scottish Deerhound")
Breed.create(breed: "Scottish Terrier")
Breed.create(breed: "Sealyham Terrier")
Breed.create(breed: "Shetland Sheepdog")
Breed.create(breed: "Shiba Inu")
Breed.create(breed: "Shih Tzu")
Breed.create(breed: "Siberian Husky")
Breed.create(breed: "Silky ")
Breed.create(breed: "Skye ")
Breed.create(breed: "Smooth Fox Terrier")
Breed.create(breed: "Soft Coated Wheaten Terrier")
Breed.create(breed: "Spinone Italiano")
Breed.create(breed: "Staffordshire Bull Terrier")
Breed.create(breed: "Standard Poodle")
Breed.create(breed: "Standard Schnauzer")
Breed.create(breed: "Sussex Spaniel")
Breed.create(breed: "Swedish Vallhund")
Breed.create(breed: "Tibetan Mastiff")
Breed.create(breed: "Tibetan Spaniel")
Breed.create(breed: "Tibetan Terrier")
Breed.create(breed: "Toy Fox Terrier")
Breed.create(breed: "Toy Manchester Terrier")
Breed.create(breed: "Toy ")
Breed.create(breed: "Vizsla")
Breed.create(breed: "Weimaraner")
Breed.create(breed: "Welsh Springer Spaniel")
Breed.create(breed: "Welsh ")
Breed.create(breed: "West Highland White Terrier")
Breed.create(breed: "Whippet")
Breed.create(breed: "Wire Fox Terrier")
Breed.create(breed: "Wirehaired Pointing Griffon")
Breed.create(breed: "Yorkshire Terrier")
